version: "3.8"
services:
  server_hello:
    image: tigase/tigase-xmpp-server:8.0.0
    ports:
      - "8480:8080"
      - "5222:5222"
    environment:
      - DB_ROOT_USER=admin
      - DB_ROOT_PASS=admin
      - ADMIN_JID=admin@server_hello
      - ADMIN_PASSWORD=admin
    volumes:
      - ./tigase/config/tigase.conf:/home/tigase/tigase-server/etc/tigase.conf
      - ./tigase/config/config.tdsl:/home/tigase/tigase-server/etc/config.tdsl

  spade_main:
    image: spade_hello:0.2.4
    build:
      context: .
    depends_on:
      - server_hello
    deploy:
      resources:
        limits:
          memory: 512MB
